name: emoji_picker_flutter_example
description: Demonstrates how to use the emoji_picker_flutter plugin.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^3.0.1
  emoji_picker_flutter:
    path: ../
  #file: ^6.1.4

flutter:
  uses-material-design: true
