name: emoji_picker_flutter
description: A Flutter package that provides an Emoji picker widget with 1500+ emojis in 8 categories.
version: 1.6.1
homepage: https://github.com/Fintasys/emoji_picker_flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  test: ^1.21.4

flutter:
  plugin:
    platforms:
      android:
        package: com.fintasys.emoji_picker_flutter
        pluginClass: EmojiPickerFlutterPlugin
      ios:
        pluginClass: EmojiPickerFlutterPlugin
      macos:
        pluginClass: EmojiPickerFlutterPlugin
      windows:
        pluginClass: EmojiPickerFlutterPluginCApi
      linux:
        pluginClass: EmojiPickerFlutterPlugin
      web:
        pluginClass: EmojiPickerFlutterPluginWeb
        fileName: emoji_picker_flutter_web.dart
